# Generated by Django 4.2.4 on 2023-08-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='flight',
            new_name='flights',
        ),
    ]
